### PR TITLE
add Makefile

### PR DESCRIPTION
**Pull request by sjaeckel**
this allows easy building of a cross-compiled static library on linux

### CODE REVIEW

**Comment by weltling** [comment]
Thanks for the PR. Perhaps a better way were this to flow upstream. Also I'd wonder these changes could be integrated with the current cmake scripts. /cc @ptosco :)

Thanks.

**Comment by sjaeckel** [comment]
@ptosco how should I proceed to get this upstream?

**Comment by ptosco** [comment]
@sjaeckel Hi, the best way would be to check out the current wineditline SVN, apply your patch, make sure it works as intended (I have never cross-compiled myself, so I am unable to test), then diff against the current SVN and send me the patch against the current SVN. I'll then apply it and commit. Does it make sense to you?

**Comment by sjaeckel** [comment]
I just did the following:
1. download the patch from https://github.com/winlibs/wineditline/commit/20345fc885cf47759b80abfa5385dcdbc9a1f1be.patch
2. put the file to my base folder of mingweditline (I used `git svn clone`)
```
$ ls -alog
total 348
drwxr-xr-x 8   4096 Jan 31 19:33 .
drwxr-xr-x 4   4096 Jan 31 19:02 ..
-rw-r--r-- 1 230633 Jan 31 19:33 20345fc885cf47759b80abfa5385dcdbc9a1f1be.patch
-rwxr-xr-x 1    173 Jan 31 19:02 AUTHORS
drwxr-xr-x 2   4096 Jan 31 19:02 bin32
drwxr-xr-x 2   4096 Jan 31 19:02 bin64
-rwxr-xr-x 1   6529 Jan 31 19:02 ChangeLog
-rw-r--r-- 1    760 Jan 31 19:02 CMakeLists.txt
-rwxr-xr-x 1   1588 Jan 31 19:02 COPYING
-rw-r--r-- 1     15 Jan 31 19:04 .gitignore
drwxr-xr-x 2   4096 Jan 31 19:02 include
-rwxr-xr-x 1   1970 Jan 31 19:02 INSTALL
drwxr-xr-x 2   4096 Jan 31 19:02 lib32
drwxr-xr-x 2   4096 Jan 31 19:02 lib64
-rw-r--r-- 1  50904 Jan 31 19:06 libwineditline.a
-rw-r--r-- 1   1435 Jan 31 19:04 Makefile
-rwxr-xr-x 1   1764 Jan 31 19:02 README
drwxr-xr-x 5   4096 Jan 31 19:06 src
```
3. apply the patch
```
$ patch -p1 < 20345fc885cf47759b80abfa5385dcdbc9a1f1be.patch 
patching file .gitignore
patching file Makefile
patching file src/mingw_extra/Strsafe.h
patching symbolic link src/readline/readline.h
```
4. build
```
$ make CROSS_COMPILE=x86_64-w64-mingw32- V=1
x86_64-w64-mingw32-gcc -I./src/ -I./src/mingw_extra -c src/editline.c -o src/editline.o
x86_64-w64-mingw32-gcc -I./src/ -I./src/mingw_extra -c src/fn_complete.c -o src/fn_complete.o
x86_64-w64-mingw32-gcc -I./src/ -I./src/mingw_extra -c src/history.c -o src/history.o
src/history.c: In function ‘source_editrc’:
src/history.c:133:7: warning: implicit declaration of function ‘sscanf_s’ [-Wimplicit-function-declaration]
       sscanf_s(line, "%16s %16s %d",
       ^
src/history.c: In function ‘using_history’:
src/history.c:184:5: warning: implicit declaration of function ‘swscanf_s’ [-Wimplicit-function-declaration]
     swscanf_s(string_size, _T("%d"), &temp_size);
     ^
x86_64-w64-mingw32-ar r libwineditline.a src/editline.o src/fn_complete.o src/history.o
x86_64-w64-mingw32-ar: creating libwineditline.a
x86_64-w64-mingw32-ranlib libwineditline.a
```

The library itself looks fine, unfortunately I don't have a windows box available for testing.

### Possible improvements

Probably it would make sense to replace the symlink from `src/readline/readline.h` to `src/editline/readline.h` by a regular file `src/readline/readline.h` with the content 
```c
#include "../editline/readline.h"
```
as windows "isn't that good in symlink handling"^TM AFAIK :)

Is that sufficient?

**Comment by ptosco** [comment]
@sjaeckel I wouldn't create a symlink or a duplicate file. This is not a `libreadline` implementation, but a `libedit` implementation. This is why I prefer to make it very clear using a different directory name. You may always create the symlink after installation, or put appropriate `#ifdef` clauses in the code which needs to be linked to WinEditLine. Would that work for you?

**Comment by sjaeckel** [comment]
> Would that work for you?

I just had a look at the reason why I added the symlink and that's `libedit_test_readline.c`  which is not in your upstream, but in this repo... 

Also I updated the commit to remove the symlink and added a `make test` target which builds the tests (and works fine for your upstream but currently fails on this repo).

**Comment by ptosco** [comment]
Thanks for that.
Also, I wouldn't add the `Strsafe.h` header. More recent MinGW distributions do include that header:
```
paolo@WIN64 MINGW64 /c/build
$ find /c/msys64/ -name strsafe.h
/c/msys64/mingw32/i686-w64-mingw32/include/strsafe.h
/c/msys64/mingw64/x86_64-w64-mingw32/include/strsafe.h
```
So I guess you may fix that problem updating your cross-compiler headers.

**Comment by sjaeckel** [comment]
> Also, I wouldn't add the Strsafe.h header.

alright, so this looks like a "legacy-support" PR

> ...updating your cross-compiler headers

yeah, I've seen that as well, but most Linux distros ship older versions, but I guess I'll simply create a mirror of your upstream repo which contains these changes for cross-compilation and I'll update as required from my side.

thanks for your input&feedback

if that's fine for you we can close this PR then

**Comment by ptosco** [comment]
Sure, that's fine for me. So you are happy for me not to patch anything on my side, correct?

**Comment by sjaeckel** [comment]
> correct

correct :)

I thought it'd be a nice addition, but apparently it's more like "support for an uncommon build target"

**Comment by ptosco** [comment]
OK, good. Feel free to contact me if you need anything else.

**Comment by sjaeckel** [comment]
> Feel free to contact me if you need anything else.

thx!

https://github.com/sjaeckel/WinEditLine.svn

**Pull request closed without merging**
